# Author: Jianbo Zhu (jbzhu2011@gmail.com)
#
# blade BUILD file for common handlers provided by 'leopard'

cc_library(
    name = 'gflags_handler',
    srcs = 'gflags_handler.cpp',
    deps = [ 
      '#gflags',
      '#glog',
])
