# Author: Jianbo Zhu (jbzhu2011@gmail.com)
#
# blade BUILD file for an example to show how to use 'rabbit'

cc_binary(
  name = 'example',
  srcs = [ 'example.cpp' ],
  deps = [ 
        '//cpp_rabbit/rabbit/rabbit:rabbit',
])