# Author: Jianbo Zhu (jbzhu2011@gmail.com)
#
# blade BUILD file for an example to show how to use 'leopard'

cc_binary(
  name = 'example',
  srcs = [ 'example.cpp' ],
  deps = [ 
        '//cpp_leopard/leopard/leopard:leopard',
])
